FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/backend/package*.json ./packages/backend/

RUN npm set-script prepare ""
RUN npm ci -w packages/backend --omit=dev

COPY ./packages/backend/ ./packages/backend/

RUN npm run build -w packages/backend 

EXPOSE 4000

CMD ["node", "packages/backend/dist/main.js"]