version: "3.8"
services:
  backend:
    build:
      dockerfile: Dockerfile.backend
    ports:
      - "4000:4000"
    environment:
      - MYSQL_URL=http://localhost:3306

  frontend:
    build:
      dockerfile: Dockerfile.frontend
      args:
        API_URL: http://localhost:4000
    ports:
      - "3000:3000"

  db:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_DATABASE=chat
      - MYSQL_ROOT_PASSWORD=superhemligt
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:
    driver: local
