FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./package*.json ./
COPY ./packages/frontend/package*.json ./packages/frontend/

RUN npm set-script prepare ""
RUN npm ci -w packages/frontend

COPY ./packages/frontend/ ./packages/frontend/

ARG API_URL
ENV NEXT_PUBLIC_API_URL ${API_URL}
RUN npm run build -w packages/frontend

EXPOSE 3000

CMD ["npm", "run", "start", "-w", "packages/frontend"]