import { Box, Container, Heading, VStack } from "@chakra-ui/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useRef, useState } from "react";
import ChatInput from "../components/chat-input";
import MessageBox from "../components/message-box";
import * as api from "../lib/api";
import { parseJwt } from "../lib/parse-jwt";
import { Message } from "../lib/types";

export default function Home() {
  const [messages, setMessages] = useState<Message[]>([]);
  const [userId, setUserId] = useState<number>(-1);
  const messageContainerRef = useRef<HTMLDivElement>(null);

  const router = useRouter();

  const getMessages = async () => {
    const messages = await api.getMessages();
    if (messages) {
      setMessages(messages);
    }
  };

  useEffect(() => {
    const token = localStorage.getItem("chat-jwt-token");
    if (!token) {
      router.push("/login");
    } else {
      setUserId(parseJwt(token).sub);
    }

    getMessages();
  }, [router]);

  useEffect(() => {
    if (messageContainerRef.current) {
      messageContainerRef.current.scrollTop =
        messageContainerRef.current.scrollHeight;
    }
  }, [messages]);

  const onSend = async () => {
    await getMessages();
  };

  return (
    <Container maxW="lg" h="100vh">
      <Head>
        <title>Chat</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <VStack alignItems="start" h="100vh">
        <Heading as="h1">Chat</Heading>
        <VStack
          flexGrow={1}
          w="100%"
          alignItems="start"
          overflow="scroll"
          ref={messageContainerRef}
        >
          {messages.map((message) => (
            <MessageBox key={message.id} message={message} userId={userId} />
          ))}
        </VStack>
        <Box w="100%" pb={4}>
          <ChatInput onSend={onSend} />
        </Box>
      </VStack>
    </Container>
  );
}
