name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - run: npm ci
      - run: npm -w packages/backend run lint:nowarnings
      - run: npm -w packages/backend run test
      - run: npm -w packages/backend run build
      - run: npx -w packages/frontend eslint . --max-warnings=0
      - run: npm -w packages/frontend run test
      - run: npm -w packages/frontend run build
